events {}

http {
    resolver 127.0.0.11 ipv6=off;

    map $host $upstream_8042 {
        hostnames;
        ~^(?<onlyhost>.*slave.*)(:\d+)?$ $onlyhost:8042;
        default 127.0.0.1:80;
    }

    map $host $upstream_9864 {
        hostnames;
        ~^(?<onlyhost>.*slave.*)(:\d+)?$ $onlyhost:9864;
        default 127.0.0.1:80;
    }

	 map $host $upstream_8081 {
        hostnames;
        ~^(?<onlyhost>.*slave.*)(:\d+)?$ $onlyhost:8081;
        default 127.0.0.1:80;
    }

    server {
        listen 8042 default_server;

        location / {
            proxy_pass http://$upstream_8042;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_redirect ~^http://[^/]+(/.*)?$ http://$host:8042$1;
        }
    }

    server {
        listen 9864;

        location / {
            proxy_pass http://$upstream_9864;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_redirect ~^http://[^/]+(/.*)?$ http://$host:9864$1;
        }
    }

	server {
        listen 8081;

        location / {
            proxy_pass http://$upstream_8081;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_redirect ~^http://[^/]+(/.*)?$ http://$host:8081$1;
        }
    }
}
