spark.eventLog.enabled                           true

# History Server Logs (docker version)
spark.history.fs.logDirectory                   hdfs://spark-cluster-master:9000/shared/spark-logs
spark.yarn.historyServer.address                spark-cluster-master:18080
spark.eventLog.dir                              hdfs://spark-cluster-master:9000/shared/spark-logs

spark.yarn.maxAppAttempts						1
spark.driver.maxResultSize                      2g
spark.network.timeout                           600s
spark.executor.heartbeatInterval                300s
