spark.eventLog.enabled                           true

# History Server Logs (docker version)
spark.history.fs.logDirectory                   hdfs://spark-cluster-master:9000/shared/spark-logs
spark.yarn.historyServer.address                spark-cluster-master:18080
spark.eventLog.dir                              hdfs://spark-cluster-master:9000/shared/spark-logs

spark.yarn.maxAppAttempts						1
spark.driver.maxResultSize                      2g
spark.network.timeout                           600s
spark.executor.heartbeatInterval                300s

# Keep the Hadoop clients bundled with Spark; do not mix server JARs.
spark.yarn.populateHadoopClasspath               false
spark.pyspark.python                            /opt/pyspark/bin/python
spark.driver.extraJavaOptions                   -Dio.netty.tryReflectionSetAccessible=true
spark.executor.extraJavaOptions                 -Dio.netty.tryReflectionSetAccessible=true
spark.yarn.am.extraJavaOptions                  -Dio.netty.tryReflectionSetAccessible=true
